# ===================================================================
# CONFIGURAÇÃO DO BANCO DE DADOS MYSQL REAIS (WORKBENCH)
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/papelaria_guara?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Dialeto do MySQL para o Hibernate conversar com o banco corretamente
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===================================================================
# JPA / HIBERNATE CONFIGS
# ===================================================================
# Cria as tabelas automaticamente se elas não existirem no MySQL
spring.jpa.hibernate.ddl-auto=update
# Mostra os comandos SQL que o Java está executando no terminal
spring.jpa.show-sql=true

# ===================================================================
# CONFIGURAÇÃO DO SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# DESATIVADO: Banco em Memória H2 (Comentado para não ser usado)
# ===================================================================
# spring.datasource.url=jdbc:h2:mem:papelaria_guara;DB_CLOSE_DELAY=-1;MODE=MySQL
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=false